### ISSUE TITLE
The keyboard closes when I click on one of the keys

### ISSUE THREAD

**Issue by chesnel** [mafu-d/jqbtk#4]
Your plugins is exactly what I'm looking for, unfortunately when I test it, even on your website the keyboard closes when I try to press the keys. An idea? Thanks you :)

**Comment by mafu-d** [comment]
What OS/browser are you using? The keyboard is intended for use on touchscreens, so doesn't play nicely with a traditional mouse. I've also had some problems with older versions of Windows that handled touch events differently. Essentially, if the browser thinks it's a touch event, it will work; if it thinks it's a mouse, it probably won't.

**Comment by chesnel** [comment]
I'm under linux with a chrome browser (chromium). I use a touch screen, that's why I want to use your plugins. By cons the tactile has the same behavior as a mouse, which is why it does not work :) I will see if I can adapt it :)

**Comment by bevinhex** [comment]
I just fixed the issue, also added inline functionality, and click event handling, going to commit code now

**Comment by mafu-d** [comment]
Thanks, pull request merged. #5
